// <auto-generated />
using System;
using CebuSurvivalGuide.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CebuSurvivalGuide.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009092529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("CebuSurvivalGuide.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Transport basics for visitors.",
                            Name = "Getting Around"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Staying safe in Cebu.",
                            Name = "Safety"
                        });
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.CommunityMadePage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("CommunityMadePages");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.EmergencyContact", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.HasKey("Id");

                    b.HasIndex("ServiceType");

                    b.ToTable("EmergencyContacts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "",
                            Description = "Crime, theft, or immediate danger.",
                            PhoneNumber = "911",
                            ServiceName = "Police",
                            ServiceType = "police",
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = 2L,
                            Address = "",
                            Description = "Fires, explosions, and rescue situations.",
                            PhoneNumber = "911",
                            ServiceName = "Fire Department",
                            ServiceType = "fire",
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = 3L,
                            Address = "",
                            Description = "Serious injury or sudden illness needing urgent care.",
                            PhoneNumber = "911",
                            ServiceName = "Ambulance / Medical Emergency",
                            ServiceType = "medical",
                            WebsiteUrl = ""
                        },
                        new
                        {
                            Id = 4L,
                            Address = "",
                            Description = "First aid, blood services, and disaster response.",
                            PhoneNumber = "143",
                            ServiceName = "Philippine Red Cross",
                            ServiceType = "disaster",
                            WebsiteUrl = "https://redcross.org.ph"
                        });
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.Guide", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Guides");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Content = "Flag the jeepney down, pass your fare forward, and say 'para' when you want to get off. (Sample content)",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Riding a jeepney",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            Content = "Save 911 in your phone and know the nearest hospital before you travel. (Sample content)",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Emergency basics",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.JeepRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fare")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("OperatingHours")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("StartingPoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VehicleType");

                    b.ToTable("JeepRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Via Mango Avenue (sample data)",
                            Destination = "Colon",
                            Fare = "",
                            OperatingHours = "",
                            RouteName = "04L",
                            SourceUrl = "",
                            StartingPoint = "Lahug",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Jeepney"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Via Osmeña Blvd (sample data)",
                            Destination = "Carbon Market",
                            Fare = "",
                            OperatingHours = "",
                            RouteName = "17B",
                            SourceUrl = "",
                            StartingPoint = "Ayala Center",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Jeepney"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Via Escario Street (sample data)",
                            Destination = "SM City",
                            Fare = "",
                            OperatingHours = "",
                            RouteName = "01K",
                            SourceUrl = "",
                            StartingPoint = "Talamban",
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehicleType = "Jeepney"
                        });
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.JeepStop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StopOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId", "StopOrder")
                        .IsUnique();

                    b.ToTable("JeepStops", t =>
                        {
                            t.HasCheckConstraint("CK_JeepStops_StopOrder", "StopOrder >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            RouteId = 1L,
                            StopName = "Lahug",
                            StopOrder = 0
                        },
                        new
                        {
                            Id = 2L,
                            RouteId = 1L,
                            StopName = "JY Square",
                            StopOrder = 1
                        },
                        new
                        {
                            Id = 3L,
                            RouteId = 1L,
                            StopName = "Mango Avenue",
                            StopOrder = 2
                        },
                        new
                        {
                            Id = 4L,
                            RouteId = 1L,
                            StopName = "Fuente Osmeña",
                            StopOrder = 3
                        },
                        new
                        {
                            Id = 5L,
                            RouteId = 1L,
                            StopName = "Colon",
                            StopOrder = 4
                        },
                        new
                        {
                            Id = 6L,
                            RouteId = 2L,
                            StopName = "Ayala Center",
                            StopOrder = 0
                        },
                        new
                        {
                            Id = 7L,
                            RouteId = 2L,
                            StopName = "Cebu Business Park",
                            StopOrder = 1
                        },
                        new
                        {
                            Id = 8L,
                            RouteId = 2L,
                            StopName = "Osmeña Blvd",
                            StopOrder = 2
                        },
                        new
                        {
                            Id = 9L,
                            RouteId = 2L,
                            StopName = "Carbon Market",
                            StopOrder = 3
                        },
                        new
                        {
                            Id = 10L,
                            RouteId = 3L,
                            StopName = "Talamban",
                            StopOrder = 0
                        },
                        new
                        {
                            Id = 11L,
                            RouteId = 3L,
                            StopName = "Gorordo Avenue",
                            StopOrder = 1
                        },
                        new
                        {
                            Id = 12L,
                            RouteId = 3L,
                            StopName = "Escario Street",
                            StopOrder = 2
                        },
                        new
                        {
                            Id = 13L,
                            RouteId = 3L,
                            StopName = "SM City",
                            StopOrder = 3
                        });
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Phrase")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "Greetings",
                            Description = "",
                            Phrase = "Salamat",
                            Pronunciation = "sah-LAH-maht",
                            Translation = "Thank you"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "Greetings",
                            Description = "",
                            Phrase = "Palihug",
                            Pronunciation = "pah-lee-HOOG",
                            Translation = "Please"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "Shopping",
                            Description = "",
                            Phrase = "Pila ni?",
                            Pronunciation = "PEE-lah nee",
                            Translation = "How much is this?"
                        });
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.NewsArticle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublishedAt");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.Source", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("");

                    b.Property<long>("GuideId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GuideId");

                    b.ToTable("Sources");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Replace with a real reference.",
                            GuideId = 1L,
                            Name = "Placeholder source",
                            Url = "https://example.com/jeepney"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Replace with a real reference.",
                            GuideId = 2L,
                            Name = "Placeholder source",
                            Url = "https://example.com/safety"
                        });
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("member");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.CommunityMadePage", b =>
                {
                    b.HasOne("CebuSurvivalGuide.Models.User", "User")
                        .WithMany("Pages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.Guide", b =>
                {
                    b.HasOne("CebuSurvivalGuide.Models.Category", "Category")
                        .WithMany("Guides")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.JeepStop", b =>
                {
                    b.HasOne("CebuSurvivalGuide.Models.JeepRoute", "Route")
                        .WithMany("Stops")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.Source", b =>
                {
                    b.HasOne("CebuSurvivalGuide.Models.Guide", "Guide")
                        .WithMany("Sources")
                        .HasForeignKey("GuideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guide");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.Category", b =>
                {
                    b.Navigation("Guides");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.Guide", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.JeepRoute", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("CebuSurvivalGuide.Models.User", b =>
                {
                    b.Navigation("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
